### ISSUE TITLE
Gnome Keyring problem

### ISSUE THREAD

**Issue by fortizc** [dkosmari/gnome-shell-extension-totp#2]
Hi, I think I found a prioblem, after to lock my secretes the extension fails when I try to unlock them.  I see the following message:
```
No such secret item at path: /org/freedesktop/secrets/collection/login/5
```
I tried to use the unlock / lock button on the settings with the same results... the most annoying thing is that right now the extension is not listing my OTP secrets in the systray, I need to go to the extension settings to copy them

**Comment by fortizc** [comment]
The error seems to come from https://github.com/dkosmari/gnome-shell-extension-totp/blob/master/secretUtils.js#L49

**Comment by dkosmari** [comment]
I've seen this happens when doing things like setting a keyring to auto unlock during login. That is, you unlock a collection, and keep the "Automatically unlock this keyring..." checkbox on. At that very moment, something goes wrong inside the GNOME Keyring Daemon.

Restarting the GNOME Keyring Daemon (or just logging out and back in again) seems to resolve the problem. See if this works for you:

    killall gnome-keyring-daemon

Then try to access your OTP secrets, it should start `gnome-keyring-daemon` automatically, and the bug should be gone.

**Comment by fortizc** [comment]
Thanks, the workaround works! so this is a Gnome Keyring problem?

**Comment by dkosmari** [comment]
As far as I can tell, yes, it's a GNOME Keyring bug.

I submitted a bug: https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/149
